automated deploy main branch

diff --git a/.github/workflows/deploy.yml b/.github/workflows/deploy.yml
--- a/.github/workflows/deploy.yml
+++ b/.github/workflows/deploy.yml
@@ -27,13 +27,20 @@ jobs:
       - name: Show JARs in build/libs
         run: |
           echo "Contents of build/libs:"
-          ls -la build/libs
+          ls -la build/
+
+      - name: Verify app.jar exists
+        run: |
+          if [ ! -f app.jar ]; then
+           echo "app.jar not found!"
+           exit 1
+          fi
 
       - name: Rename jar for Docker
         run: |
           JAR=$(find build/libs -name '*-SNAPSHOT.jar' ! -name '*-plain.jar' | head -n 1)
           echo "Found jar: $JAR"
-          mv "$JAR" app.jar
+          cp "$JAR" ./app.jar
 
       - name: List files in workspace root before SCP
         run: ls -la
